### ISSUE TITLE
use unittest.mock instead of mock

### ISSUE THREAD

**Issue by pgajdos** [codrsquad/setupmeta#75]
Could you please consider to utilize unittest.mock as a fallback (given you still support Python 2)?

Background:
https://fedoraproject.org/wiki/Changes/DeprecatePythonMock
https://trello.com/c/S6eADbii/64-remove-python-mock

**Comment by zsimic** [comment]
Done, thank you! setupmeta `v3.3.1` does not use `mock` anymore but `unittest.mock` (also, got rid of `six`)

**Comment by pgajdos** [comment]
Thanks!
